kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
  - name: auth-provider-gcp
    matchImages:
      - "container.cloud.google.com"
      - "gcr.io"
      - "*.gcr.io"
      - "*.pkg.dev"
    defaultCacheDuration: "1m"
    args:
      - get-credentials
